run:
  framework: ldm
  mode: aleatoric
  task: custom
  output_dir: outputs
  experiment_name: ldm_aleatoric_experiment
  epoch: latest
  checkpoint_root: checkpoints
model:
  in_ch: 6
  out_ch: 3
  vae_ckpt: /mimer/NOBACKUP/groups/naiss2023-6-336/fdifeola/diffusion/checkpoints/T1T2/VAE
  diff_ckpt: /mimer/NOBACKUP/groups/naiss2023-6-336/fdifeola/diffusion/checkpoints/T1T2/LDM_aleatoric_T1T2/diffusion-ep-300.pth
  context_ckpt: null
  backbone_class: null
  backbone_kwargs: {}
  vae_class: null
  vae_kwargs: {}
inference:
  batch_size: 1
  num_workers: 4
  num_train_timesteps: 1000
  num_inference_steps: 50
  beta_start: 0.0015
  beta_end: 0.0205
  beta_schedule: scaled_linear_beta
  K: 10
  seed: 0
data:
  dataset_class: t1t2
  dataset_kwargs:
    annotation_A: /mimer/NOBACKUP/groups/snic2022-5-277/cadornato/Data/annotations_A.csv
    annotation_B: /mimer/NOBACKUP/groups/snic2022-5-277/cadornato/Data/annotations_B.csv
  scaling_factor: 9.404202
analysis:
  metrics: true
  sparsification: false
  spatial_error_correlation: false
  calibration_bins: false
