run:
  framework: dm
  mode: aleatoric
  task: custom
  output_dir: outputs/checkpoints
  experiment_name: dm_aleatoric_experiment
model:
  in_ch: 2
  out_ch: 1
  diff_ckpt: null
  vae_ckpt: null
  context_ckpt: null
  spatial_enc_channels: 1
  cross_attention_dim: 128
  backbone_class: null
  backbone_kwargs: {}
  vae_class: null
  vae_kwargs: {}
data:
  dataset_class: latent_uq.data.example_dataset.RandomPairedDataset
  dataset_kwargs:
    length: 8
    channels: 1
    height: 256
    width: 256
training:
  batch_size: 2
  num_workers: 4
  n_epochs: 1
  lr: 1.5e-05
  diff_loss_weight: 1.0
  backend: generic
  loss_class: null
  loss_kwargs: {}
